# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-Shopper18' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOS-Shopper18
  pod 'XLForm'
  pod 'JVFloatLabeledTextField', '1.0.2', :inhibit_warnings => true
  pod 'SDWebImage'
  #pod 'ReactiveCocoa'
  pod 'libextobjc'
  pod 'surveymonkey-ios-sdk'
  pod 'TWMessageBarManager'
  pod 'SVProgressHUD'
  pod 'Braintree'
  pod 'BraintreeDropIn'
  pod 'Braintree/PayPal'

end
